# Generated by Django 5.1.6 on 2025-02-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='adminreg',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminreg',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminreg',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
